# Generated by Django 3.2.4 on 2021-06-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
