# Generated by Django 3.2.4 on 2021-06-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesupload',
            name='type_fichier',
            field=models.TextField(blank=True, max_length=30, verbose_name='Type de fichier'),
        ),
    ]
