# Generated by Django 3.2.4 on 2021-06-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_filesupload_type_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='file',
            field=models.FileField(db_column='fichiers', upload_to='media/'),
        ),
    ]
