# Generated by Django 3.2.4 on 2021-06-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_filesupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='fichiers',
        ),
        migrations.AddField(
            model_name='filesupload',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.utilisateur'),
        ),
    ]
