# Generated by Django 3.2.4 on 2021-06-16 14:46

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210616_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='file',
            field=models.FileField(upload_to=pages.models.user_directory_path),
        ),
    ]
